#### Learning objectives: 
Comment on the emergence of microbial life and the evolution of Earth systems

* Indicate the key events in the evolution of Earth systems at each approximate moment in the time series. If times need to be adjusted or added to the timeline to fully account for the development of Earth systems, please do so. 

    + 4.6 billion years ago  
        + Solar system formed. Inner planets received water vapour and carbon. At this time, there was high carbon dioxide concetration, vapour pressure and temprature was at 500 degree Celcius.
    + 4.5 billion years ago 
        + Moon was formed which allowed the earth to spin, tils, have day/night cycles and different seasons. 
    + 4.4 billion years ago 
        + Zircon (the oldest minirals) formed
        + Earth had decreased in temperature at 100 degree Celcius
    + Between 4.4 and 4.1 billion years ago
        + A meteor impact
    + 4.1 billion years ago  
        + Evidence of life found in Zircons
    + 4.0 billion years ago  
        + The oldest rock: Acastagneiss
        + There was evidence of plate subduction
        + Greenhouse carbon dioxide increased
        + Metorite bombardment halted and sea water chemistry stablized.
    + 3.8 billion years ago  
        + Chemical fossils such as carbon isotypes found in rocks which provides another evidence for early life. Use of C-12 suggests possibiity for phosynthesis. However, non-photosysnthetic autotrophs can also produce C-12.
    + 3.5 billion years ago  
        + Structural fossils such presence of stromatolites (bacterial aggregations) found in rocks. 
        + Early methanogensis. 
    + 3.0 billion years ago  
        + A glaciation occured.
        + Early cyanobacteria, evidence for photosynthesis
        + Great oxidations event
        + life on land
    + 2.7 billion years ago  
        + Emergence of prokaryotes
    + 2.2 billion years ago  
        + rock recognized as red beds
        + Oxygen levels increased sharply
    + 2.1 billion years ago
    + 1.8 billion years ago
    + 1.3 billion years ago
    
    + 550,000 years ago
        + Cambrian explosion, expansion of multicellular evolution
        + Denovian explosion, emergence of woody land plants
        + Caboniferous period, presence of fish cephalopds, corals
        + Formation of Pange resulted in dry, harsh climate in Pangea's interior and also there increased competition among species as they were being clusted in one giant land mass.
        + Permian extrintion, 95% of species gone
      + 400,000 billion years ago 
        + Increased in oxygen levels again, resulted in rise of giants
        + Hence, rise of dinosaurs
        + Cretaceous-Tertiary extinction event, which resulted in nothing over 10kg of an organims existed.
        + Increased in mammal size, and diversification
        + Dramatic global warming
        + Ice age event
        + Grass started to dominate the forest
    + 200,000 years ago
        + Homosapiens first appeared


* Describe the dominant physical and chemical characteristics of Earth systems at the following waypoints:  

    + Hadean  
        + With the temeprature of 500 degree Celcius and high levels of carbon diaxide  and water vapous, the Earth is practically a molten object.
    
    + Archean  
        + A glaciation occured.
        + Soon after the planet became brown and hazy due methanogenesis. Methane produce by methanogens help keep Earth warm. Otherwise, the Earth would have stayed frozen and perhaps no life would have existed.
    + Precambrian
        + Phosynthesis evolves, result ing some oxygen in the atmosphere.
    + Proterozoic  
      + During early proterozoic, another glaciation event occured. Once again, the Earth system has "shut down".
          + Oxygen and atmospheric methane =  carbon dioxide. This caused a net decrease in greenhouse gas effects, making earth cold and leading to glaciation. 
      + The oxygen also started oxidizing iron forming banded irons, as seen in sedimentary rock.

    + Phanerozoic  
      + There was an increased oxygenation of the atmosphere
      + Plants started to evolve 
      + Coal deposits from dead organisms caused by multiple extiction events were stored in sediments
      + Once again, glaciation occured at various periods
